// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Candy Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi

type BuyCandy400Response struct {
	Error string `json:"error,omitempty"`
}

// AssertBuyCandy400ResponseRequired checks if the required fields are not zero-ed
func AssertBuyCandy400ResponseRequired(obj BuyCandy400Response) error {
	return nil
}

// AssertBuyCandy400ResponseConstraints checks if the values respects the defined constraints
func AssertBuyCandy400ResponseConstraints(obj BuyCandy400Response) error {
	return nil
}
