openapi: 3.0.1
info:
  title: Candy Server
  version: 1.0.0
servers:
- url: /
paths:
  /buy_candy:
    post:
      operationId: buyCandy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/buyCandy_request'
        description: summary of the candy order
        required: false
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buyCandy_201_response'
          description: purchase succesful
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buyCandy_400_response'
          description: some error in input data
        "402":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buyCandy_400_response'
          description: not enough money
      x-codegen-request-body-name: order
components:
  schemas:
    buyCandy_201_response:
      example:
        thanks: thanks
        change: 0
      properties:
        thanks:
          type: string
        change:
          type: integer
      type: object
    buyCandy_request:
      properties:
        money:
          description: amount of money put into vending machine
          type: integer
        candyType:
          description: kind of candy
          type: string
        candyCount:
          description: number of candy
          type: integer
      required:
      - candyCount
      - candyType
      - money
      type: object
    buyCandy_400_response:
      example:
        error: error
      properties:
        error:
          type: string
      type: object
x-original-swagger-version: "2.0"
